version: '2.1'

services:
  mongodb:
    image: mongo:latest
    command: --smallfiles
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: alf
      #MONGO_INITDB_ROOT_PASSWORD: alf  
    ports:
      - "27017:27017"
    networks:
      - docomo.fraudwall
    restart: always

  kafka:
    image: landoop/fast-data-dev
    container_name: kafka
    hostname: kafka
    ports:
     - "2181:2181"
     - "3030:3030"
     - "8081:8081"
     - "8082:8082"
     - "8083:8083"
     - "9092:9092"
    environment:
      ADV_HOST: localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      SAMPLEDATA: 0
      BROWSECONFIGS: 1
      RUNTESTS: 0
      DEBUG: 1
    networks:
    - docomo.fraudwall
    #command:    
    #- /opt/landoop/kafka/bin/kafka-topics --create --zookeeper localhost:2181 --replication-factor 1 --partitions 100 --topic FRAUD-WALL-NEW

networks:
  docomo.fraudwall:
    driver: bridge